export const name = "001_box_scores";

export function up(db) {
	db.exec(`
    CREATE TABLE games (
      gid          INTEGER PRIMARY KEY,
      season       INTEGER NOT NULL,
      day          INTEGER,
      att          INTEGER,
      overtimes    INTEGER NOT NULL DEFAULT 0,
      num_periods  INTEGER NOT NULL DEFAULT 4,
      playoffs     INTEGER NOT NULL DEFAULT 0,
      finals       INTEGER NOT NULL DEFAULT 0,
      neutral_site INTEGER NOT NULL DEFAULT 0,
      won_tid      INTEGER NOT NULL,
      won_pts      INTEGER NOT NULL,
      lost_tid     INTEGER NOT NULL,
      lost_pts     INTEGER NOT NULL
    );

    CREATE TABLE game_teams (
      id           INTEGER PRIMARY KEY,
      gid          INTEGER NOT NULL REFERENCES games(gid),
      tid          INTEGER NOT NULL,
      pts          INTEGER NOT NULL,
      pts_qtrs     TEXT NOT NULL,
      ovr          INTEGER,
      won          INTEGER,
      lost         INTEGER,
      tied         INTEGER,
      otl          INTEGER,
      playoff_seed  INTEGER,
      playoff_won  INTEGER,
      playoff_lost INTEGER,
      drives INTEGER, tot_start_yds INTEGER, time_pos INTEGER, sk_alw INTEGER,
      tp INTEGER, tpa INTEGER,
      pss_cmp INTEGER, pss INTEGER, pss_yds INTEGER, pss_td INTEGER,
      pss_int INTEGER, pss_lng INTEGER, pss_sk INTEGER, pss_sk_yds INTEGER,
      rus INTEGER, rus_yds INTEGER, rus_td INTEGER, rus_lng INTEGER,
      tgt INTEGER, rec INTEGER, rec_yds INTEGER, rec_td INTEGER, rec_lng INTEGER,
      pr INTEGER, pr_yds INTEGER, pr_td INTEGER, pr_lng INTEGER,
      kr INTEGER, kr_yds INTEGER, kr_td INTEGER, kr_lng INTEGER,
      def_int INTEGER, def_int_yds INTEGER, def_int_td INTEGER, def_int_lng INTEGER,
      def_pss_def INTEGER,
      def_fmb_frc INTEGER, def_fmb_rec INTEGER, def_fmb_yds INTEGER,
      def_fmb_td INTEGER, def_fmb_lng INTEGER,
      def_sk INTEGER, def_tck_solo INTEGER, def_tck_ast INTEGER,
      def_tck_loss INTEGER, def_sft INTEGER,
      fmb INTEGER, fmb_lost INTEGER,
      fg0 INTEGER, fga0 INTEGER, fg20 INTEGER, fga20 INTEGER,
      fg30 INTEGER, fga30 INTEGER, fg40 INTEGER, fga40 INTEGER,
      fg50 INTEGER, fga50 INTEGER, fg_lng INTEGER,
      xp INTEGER, xpa INTEGER,
      ko INTEGER, ko_yds INTEGER, ko_tb INTEGER,
      ok INTEGER, ok_rec INTEGER,
      pnt INTEGER, pnt_yds INTEGER, pnt_lng INTEGER,
      pnt_tb INTEGER, pnt_in20 INTEGER, pnt_blk INTEGER,
      pen INTEGER, pen_yds INTEGER,
      pbw INTEGER, pba INTEGER, rbw INTEGER, rba INTEGER,
      UNIQUE(gid, tid)
    );

    CREATE TABLE game_players (
      id                     INTEGER PRIMARY KEY,
      gid                    INTEGER NOT NULL REFERENCES games(gid),
      tid                    INTEGER NOT NULL,
      pid                    INTEGER NOT NULL,
      name                   TEXT NOT NULL,
      pos                    TEXT,
      skills                 TEXT,
      injury_type            TEXT,
      injury_games_remaining INTEGER,
      injury_new_this_game   INTEGER,
      injury_playing_through INTEGER,
      injury_at_start        TEXT,
      gp INTEGER, gs INTEGER, min REAL,
      fmb INTEGER, fmb_lost INTEGER,
      pss_cmp INTEGER, pss INTEGER, pss_yds INTEGER, pss_td INTEGER,
      pss_int INTEGER, pss_lng INTEGER, pss_sk INTEGER, pss_sk_yds INTEGER,
      rus INTEGER, rus_yds INTEGER, rus_td INTEGER, rus_lng INTEGER,
      tgt INTEGER, rec INTEGER, rec_yds INTEGER, rec_td INTEGER, rec_lng INTEGER,
      pr INTEGER, pr_yds INTEGER, pr_td INTEGER, pr_lng INTEGER,
      kr INTEGER, kr_yds INTEGER, kr_td INTEGER, kr_lng INTEGER,
      def_int INTEGER, def_int_yds INTEGER, def_int_td INTEGER, def_int_lng INTEGER,
      def_pss_def INTEGER,
      def_fmb_frc INTEGER, def_fmb_rec INTEGER, def_fmb_yds INTEGER,
      def_fmb_td INTEGER, def_fmb_lng INTEGER,
      def_sk INTEGER, def_tck_solo INTEGER, def_tck_ast INTEGER,
      def_tck_loss INTEGER, def_sft INTEGER,
      fg0 INTEGER, fga0 INTEGER, fg20 INTEGER, fga20 INTEGER,
      fg30 INTEGER, fga30 INTEGER, fg40 INTEGER, fga40 INTEGER,
      fg50 INTEGER, fga50 INTEGER, fg_lng INTEGER,
      xp INTEGER, xpa INTEGER,
      ko INTEGER, ko_yds INTEGER, ko_tb INTEGER,
      ok INTEGER, ok_rec INTEGER,
      pnt INTEGER, pnt_yds INTEGER, pnt_lng INTEGER,
      pnt_tb INTEGER, pnt_in20 INTEGER, pnt_blk INTEGER,
      pen INTEGER, pen_yds INTEGER,
      pbw INTEGER, pba INTEGER, rbw INTEGER, rba INTEGER,
      UNIQUE(gid, pid)
    );

    CREATE TABLE game_scoring_plays (
      id         INTEGER PRIMARY KEY,
      gid        INTEGER NOT NULL REFERENCES games(gid),
      seq        INTEGER NOT NULL,
      quarter    INTEGER NOT NULL,
      clock      INTEGER NOT NULL,
      tid        INTEGER NOT NULL,
      pid        INTEGER,
      passer_pid INTEGER,
      yds        INTEGER,
      play_type  TEXT NOT NULL,
      made       INTEGER,
      pts_scored INTEGER NOT NULL,
      UNIQUE(gid, seq)
    );
  `);
}
